In [2]:
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier

a = pd.read_csv("intrusion_data_combined.csv",sep=",", header=0)


label_encoder = preprocessing.LabelEncoder()
a['protocol_type']= label_encoder.fit_transform(a['protocol_type'])  
a['service']= label_encoder.fit_transform(a['service'])  
a['flag']= label_encoder.fit_transform(a['flag'])  
a['flag']= label_encoder.fit_transform(a['flag'])
a['xAttack']= label_encoder.fit_transform(a['xAttack'])  


X = a.iloc[:, :-2].values
y = a.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15, random_state = 0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

classifier = svm.SVC()
classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)

ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
#print(ac)
#print(cm)
print(confusion_matrix(y_test, y_pred))
print("Accuracy:",metrics.accuracy_score(y_test,y_pred)) 
print(metrics.classification_report(y_test,y_pred))
print("Accuracy of the Model : " , ac)

[[ 7384    37     2     0     0]
 [   13 10578    43    22     1]
 [    6    53  1880     0     1]
 [    3   124     1   221     1]
 [    0    12     1     1    12]]
Accuracy: 0.9842616199254756
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7423
           1       0.98      0.99      0.99     10657
           2       0.98      0.97      0.97      1940
           3       0.91      0.63      0.74       350
           4       0.80      0.46      0.59        26

    accuracy                           0.98     20396
   macro avg       0.93      0.81      0.86     20396
weighted avg       0.98      0.98      0.98     20396

Accuracy of the Model :  0.9842616199254756
